name: Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:

    strategy:
      matrix:
        profile: ['checkerframework', 'errorprone', 'eclipse']

    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: "${{github.run_number}}"
      MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --no-transfer-progress"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Install maven modules
        run: ./mvnw $MAVEN_CLI_OPTS install -Dmaven.javadoc.skip -DskipTests -Dmaven.source.skip=true
      - name: Analyze with ${{ matrix.profile }}
        run: bin/analyze.sh ${{ matrix.profile }} 
